engineStrict: true
publicHoistPattern:
  - '@lezer/*'
  - '@codemirror/*'
  - 'workbox-*'
  - 'vite-plugin-pwa'
allowBuilds:
  core-js: true
  es5-ext: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.2'
