import { icons, names } from '$lib/icons';
import { loadIcon, type IconifyIcon } from 'iconify-icon';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import url from 'node:url';

const DIR_NAME = path.dirname(url.fileURLToPath(import.meta.url));
const FILE_PATH = path.join(DIR_NAME, './$icons.ts');
const FILE_TEMPLATE = `
/**
 * This file is generated by \`./preload.ts\`, do not edit this file manually.
 * Use \`npm run build:icons\` to update this file.
 */
import type { IconifyIcon } from 'iconify-icon';
import { icons as names } from './icons';

export const icons: Readonly<{ [key in keyof typeof names]: IconifyIcon }>`;

/**
 * Preload icons from the Iconify API and generate a local cache file.
 */
async function preload() {
  const data: Record<string, IconifyIcon> = {};

  console.log('Preloading icons...');
  for (const [key, name] of Object.entries(names)) {
    if (key in icons) {
      data[key] = icons[key as keyof typeof icons];
      console.log(`\x1b[34m> Loaded icon [${name}] from local cache.`);
    } else {
      try {
        data[key] = await loadIcon(name);
        console.log(`\x1b[32m> Loaded icon [${name}] from Iconify API.`);
      } catch (error) {
        console.error('\x1b[31m> Failed to load icon from Iconify API!', error);
      }
    }
  }

  console.log('\x1b[0m');
  console.log('Generating local cache file...');
  await writeFile(FILE_PATH, `${FILE_TEMPLATE} = ${JSON.stringify(data, null, 2)};`, 'utf8');
  console.log(`\x1b[32m> ${FILE_PATH}`);
  console.log('\x1b[0m');
}

preload();
