// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';
import { jsoncHighlighting } from './jsonc-highlight';
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "$bO]QPOOOOQO'#Cd'#CdOtQPO'#CgO|QPO'#ClOOQO'#Cr'#CrQOQPOOOOQO'#Ci'#CiO!TQPO'#ChO!YQPO'#CtOOQO,59R,59RO!bQPO,59RO!gQPO'#CwOOQO,59W,59WO!oQPO,59WO]QPO,59SOwQPO'#CmO!tQPO,59`OOQO1G.m1G.mO]QPO'#CnO!|QPO,59cOOQO1G.r1G.rOOQO1G.n1G.nOOQO,59X,59XOOQO-E6k-E6kOOQO,59Y,59YOOQO-E6l-E6l",
  stateData: '#U~OeOSPOSQOS~OSSOTSOUSOVSOYQO_ROgPO~OXXOgUO~O^[O~P]Oi^O~Oj_OXhX~OXaO~OjbO^kX~O^dO~Oj_OXha~OjbO^ka~O',
  goto: '!mlPPPPPPPPmPPmsyPPm}!TPPP!ZP!gPP!jXSOR^bQWQRf_TVQ_Q`WRg`QcZRicQTOQZRQe^RhbRYQR]R',
  nodeNames:
    '⚠ LineComment BlockComment JsonText True False Null Number String } { Object Property PropertyName ] [ Array',
  maxTerm: 27,
  nodeProps: [
    ['isolate', -4, 1, 2, 8, 13, ''],
    ['openedBy', 9, '{', 14, '['],
    ['closedBy', 10, '}', 15, ']']
  ],
  propSources: [jsoncHighlighting],
  skippedNodes: [0, 1, 2],
  repeatNodeCount: 2,
  tokenData:
    "*x~RbXY!ZYZ!Z]^!Zpq!Zrs!`|}$x}!O$}!P!Q&w!Q!R%W!R![&f![!](p!}#O(u#P#Q(z#Y#Z)P#b#c)n#h#i*V#o#p*n#q#r*s~!`Oe~~!cWpq!`qr!`rs!{s#O!`#O#P#Q#P;'S!`;'S;=`$r<%lO!`~#QOg~~#TXrs!`!P!Q!`#O#P!`#U#V!`#Y#Z!`#b#c!`#f#g!`#h#i!`#i#j#p~#sR!Q![#|!c!i#|#T#Z#|~$PR!Q![$Y!c!i$Y#T#Z$Y~$]R!Q![$f!c!i$f#T#Z$f~$iR!Q![!`!c!i!`#T#Z!`~$uP;=`<%l!`~$}Oj~~%QQ!Q!R%W!R![&f~%]RV~!O!P%f!g!h%z#X#Y%z~%iP!Q![%l~%qRV~!Q![%l!g!h%z#X#Y%z~%}R{|&W}!O&W!Q![&^~&ZP!Q![&^~&cPV~!Q![&^~&kSV~!O!P%f!Q![&f!g!h%z#X#Y%z~&zQz{'Q!P!Q(X~'TTOz'Qz{'d{;'S'Q;'S;=`(R<%lO'Q~'gVOz'Qz{'d{!P'Q!P!Q'|!Q;'S'Q;'S;=`(R<%lO'Q~(ROQ~~(UP;=`<%l'Q~(^SP~OY(XZ;'S(X;'S;=`(j<%lO(X~(mP;=`<%l(X~(uOi~~(zO_~~)PO^~~)SP#T#U)V~)YP#`#a)]~)`P#g#h)c~)fP#X#Y)i~)nOT~~)qP#i#j)t~)wP#`#a)z~)}P#`#a*Q~*VOU~~*YP#f#g*]~*`P#i#j*c~*fP#X#Y*i~*nOS~~*sOY~~*xOX~",
  tokenizers: [0],
  topRules: { JsonText: [0, 3] },
  tokenPrec: 0
});
