from tortoise import migrations
from tortoise.migrations import operations as ops
from app.models.download import DownloadState
from app.models.flow import GraphCategory, GraphState, IntervalUnit, JobState, JobTrigger
from app.models.media import Language, LibType
from app.models.user import UserRole
from orjson import loads
from tortoise.fields.base import OnDelete
from tortoise.fields.data import JSON_DUMPS
from tortoise import fields

class Migration(migrations.Migration):
    initial = True

    operations = [
        ops.CreateModel(
            name='DownloadDir',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('path', fields.CharField(unique=True, max_length=4096)),
                ('last_used', fields.DatetimeField(auto_now=False, auto_now_add=False)),
            ],
            options={'table': 'download_dir', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='Downloader',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('preset', fields.CharField(null=True, unique=True, max_length=16)),
                ('config', fields.TextField(unique=False)),
                ('name', fields.CharField(unique=True, max_length=64)),
                ('host', fields.CharField(null=True, max_length=255)),
                ('port', fields.IntField(null=True)),
                ('version', fields.CharField(null=True, max_length=32)),
                ('priority', fields.IntField(unique=True)),
            ],
            options={'table': 'downloader', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('downloader', fields.ForeignKeyField('models.Downloader', source_field='downloader_id', db_index=True, db_constraint=True, to_field='id', related_name='tasks', on_delete=OnDelete.CASCADE)),
                ('dir', fields.CharField(max_length=4096)),
                ('name', fields.CharField(max_length=255)),
                ('unique_id', fields.CharField(null=True, db_index=True, max_length=255)),
                ('info_hash', fields.CharField(null=True, unique=True, max_length=40)),
                ('info_hash_v2', fields.CharField(null=True, unique=True, max_length=68)),
                ('magnet_link', fields.TextField(null=True, unique=False)),
                ('state', fields.CharEnumField(description='DOWNLOADING: downloading\nPAUSED: paused\nCOMPLETED: completed\nERROR: error', enum_type=DownloadState, max_length=16)),
                ('raw_state', fields.CharField(null=True, max_length=32)),
                ('error_msg', fields.TextField(null=True, unique=False)),
                ('up_speed', fields.BigIntField(null=True)),
                ('dl_speed', fields.BigIntField(null=True)),
                ('percentage', fields.FloatField(null=True)),
                ('total_size', fields.BigIntField(null=True)),
                ('completed_size', fields.BigIntField(null=True)),
                ('completed_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ],
            options={'table': 'download_task', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowRepository',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('repo_name', fields.CharField(unique=True, max_length=255)),
                ('repo_url', fields.CharField(max_length=255)),
                ('repo_description', fields.CharField(null=True, max_length=512)),
                ('owner_name', fields.CharField(null=True, max_length=64)),
                ('owner_url', fields.CharField(null=True, max_length=255)),
                ('owner_avatar', fields.CharField(null=True, max_length=255)),
            ],
            options={'table': 'flow_repository', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('repo', fields.ForeignKeyField('models.FlowRepository', source_field='repo_id', db_index=True, db_constraint=True, to_field='repo_name', related_name='templates', on_delete=OnDelete.CASCADE)),
                ('path', fields.CharField(max_length=255)),
                ('name', fields.CharField(max_length=64)),
                ('icon', fields.CharField(null=True, max_length=255)),
                ('description', fields.CharField(null=True, max_length=255)),
                ('category', fields.CharEnumField(description='INDEXER: indexer\nINGEST: ingest\nSCHEDULE: schedule', enum_type=GraphCategory, max_length=16)),
                ('revision', fields.IntField()),
                ('definition', fields.JSONField(encoder=JSON_DUMPS, decoder=loads)),
                ('newest', fields.BooleanField(default=True)),
            ],
            options={'table': 'flow_template', 'app': 'models', 'unique_together': (('repo', 'path', 'revision'),), 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowGraph',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('tmpl', fields.ForeignKeyField('models.FlowTemplate', source_field='tmpl_id', null=True, db_index=True, db_constraint=True, to_field='id', related_name='graphs', on_delete=OnDelete.SET_NULL)),
                ('name', fields.CharField(unique=True, max_length=64)),
                ('icon', fields.CharField(null=True, max_length=255)),
                ('description', fields.CharField(null=True, max_length=255)),
                ('category', fields.CharEnumField(description='INDEXER: indexer\nINGEST: ingest\nSCHEDULE: schedule', enum_type=GraphCategory, max_length=16)),
                ('revision', fields.IntField(null=True)),
                ('state', fields.CharEnumField(description='DRAFTING: drafting\nMODIFIED: modified\nPUBLISHED: published', enum_type=GraphState, max_length=16)),
                ('draft', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('definition', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('editable', fields.BooleanField(default=True)),
            ],
            options={'table': 'flow_graph', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowInstance',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('graph', fields.ForeignKeyField('models.FlowGraph', source_field='graph_id', db_index=True, db_constraint=True, to_field='id', related_name='instances', on_delete=OnDelete.CASCADE)),
                ('definition', fields.JSONField(encoder=JSON_DUMPS, decoder=loads)),
                ('bootparams', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('context', fields.JSONField(encoder=JSON_DUMPS, decoder=loads)),
                ('repeatable', fields.BooleanField(default=False)),
                ('asynchronous', fields.BooleanField(default=False)),
                ('prev_id', fields.IntField(null=True)),
            ],
            options={'table': 'flow_instance', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowFootprint',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('inst', fields.ForeignKeyField('models.FlowInstance', source_field='inst_id', db_index=True, db_constraint=True, to_field='id', related_name='footprints', on_delete=OnDelete.CASCADE)),
                ('node_id', fields.CharField(max_length=64)),
                ('node_type', fields.CharField(max_length=64)),
                ('node_data', fields.JSONField(encoder=JSON_DUMPS, decoder=loads)),
                ('loop_id', fields.CharField(null=True, max_length=64)),
                ('started_at', fields.DatetimeField(auto_now=False, auto_now_add=False)),
                ('ended_at', fields.DatetimeField(auto_now=False, auto_now_add=False)),
            ],
            options={'table': 'flow_footprint', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowJob',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('graph', fields.ForeignKeyField('models.FlowGraph', source_field='graph_id', db_index=True, db_constraint=True, to_field='id', related_name='jobs', on_delete=OnDelete.CASCADE)),
                ('bootparams', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('repeatable', fields.BooleanField(default=False)),
                ('recoverable', fields.BooleanField(default=True)),
                ('state', fields.CharEnumField(description='PENDING: pending\nRUNNING: running\nPAUSED: paused', enum_type=JobState, max_length=16)),
                ('trigger', fields.CharEnumField(description='DATE: date\nCRON: cron\nINTERVAL: interval', enum_type=JobTrigger, max_length=16)),
                ('run_date', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('cron_expr', fields.CharField(null=True, max_length=255)),
                ('interval_num', fields.IntField(null=True)),
                ('interval_unit', fields.CharEnumField(null=True, description='WEEKS: weeks\nDAYS: days\nHOURS: hours\nMINUTES: minutes\nSECONDS: seconds', enum_type=IntervalUnit, max_length=16)),
                ('interval_start', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('interval_end', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ],
            options={'table': 'flow_job', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowLog',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('graph', fields.ForeignKeyField('models.FlowGraph', source_field='graph_id', db_index=True, db_constraint=True, to_field='id', related_name='logs', on_delete=OnDelete.CASCADE)),
                ('bootparams', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('retval', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('started_at', fields.DatetimeField(auto_now=False, auto_now_add=False)),
                ('ended_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('node_id', fields.CharField(null=True, max_length=64)),
                ('node_type', fields.CharField(null=True, max_length=64)),
                ('node_data', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('input_id', fields.CharField(null=True, max_length=64)),
                ('exc_info', fields.TextField(null=True, unique=False)),
            ],
            options={'table': 'flow_log', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowTrigger',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('graph', fields.ForeignKeyField('models.FlowGraph', source_field='graph_id', db_index=True, db_constraint=True, to_field='id', related_name='triggers', on_delete=OnDelete.CASCADE)),
                ('category', fields.CharEnumField(description='INDEXER: indexer\nINGEST: ingest\nSCHEDULE: schedule', enum_type=GraphCategory, max_length=16)),
                ('rel_id', fields.IntField()),
                ('priority', fields.IntField()),
                ('asynchronous', fields.BooleanField(default=False)),
            ],
            options={'table': 'flow_trigger', 'app': 'models', 'unique_together': (('graph', 'rel_id'), ('rel_id', 'priority')), 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='FlowVariable',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('graph', fields.ForeignKeyField('models.FlowGraph', source_field='graph_id', db_index=True, db_constraint=True, to_field='id', related_name='variables', on_delete=OnDelete.CASCADE)),
                ('key', fields.CharField(max_length=64)),
                ('value', fields.JSONField(encoder=JSON_DUMPS, decoder=loads)),
                ('expires', fields.IntField(null=True)),
            ],
            options={'table': 'flow_variable', 'app': 'models', 'unique_together': (('graph', 'key'),), 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='GlobalCookie',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('name', fields.TextField(unique=False)),
                ('value', fields.TextField(unique=False)),
                ('domain', fields.TextField(unique=False)),
                ('path', fields.TextField(unique=False)),
                ('expires', fields.IntField(null=True)),
            ],
            options={'table': 'global_cookie', 'app': 'models', 'unique_together': (('name', 'domain', 'path'),), 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('key', fields.CharField(unique=True, max_length=64)),
                ('value', fields.CharField(max_length=4096)),
                ('value_length', fields.IntField()),
                ('encrypted', fields.BooleanField()),
            ],
            options={'table': 'global_variable', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='MediaLib',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('lib_type', fields.CharEnumField(description='MOVIE: movie\nTV_SHOW: tv_show', enum_type=LibType, max_length=16)),
                ('name', fields.CharField(unique=True, max_length=64)),
                ('dir', fields.CharField(unique=True, max_length=4096)),
                ('language', fields.CharEnumField(null=True, description='EN_US: en-US\nZH_CN: zh-CN', enum_type=Language, max_length=16)),
                ('priority', fields.IntField(unique=True)),
            ],
            options={'table': 'media_lib', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='MediaEvent',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('lib', fields.ForeignKeyField('models.MediaLib', source_field='lib_id', db_index=True, db_constraint=True, to_field='id', related_name='events', on_delete=OnDelete.CASCADE)),
                ('src_path', fields.CharField(max_length=4096)),
                ('dest_path', fields.CharField(null=True, max_length=4096)),
                ('event_type', fields.CharField(max_length=16)),
                ('is_directory', fields.BooleanField(default=False)),
            ],
            options={'table': 'media_event', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='MediaItem',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('lib', fields.ForeignKeyField('models.MediaLib', source_field='lib_id', db_index=True, db_constraint=True, to_field='id', related_name='items', on_delete=OnDelete.CASCADE)),
                ('parent', fields.ForeignKeyField('models.MediaItem', source_field='parent_id', null=True, db_index=True, db_constraint=True, to_field='id', related_name='children', on_delete=OnDelete.CASCADE)),
                ('dir', fields.CharField(max_length=4096)),
                ('path', fields.CharField(max_length=4096)),
                ('name', fields.CharField(max_length=255)),
                ('visible', fields.BooleanField(default=False)),
                ('nfo_path', fields.CharField(null=True, max_length=4096)),
                ('nfo_mtime', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('title', fields.CharField(null=True, max_length=255)),
                ('year', fields.IntField(null=True)),
                ('season', fields.IntField(null=True)),
                ('episode', fields.IntField(null=True)),
                ('cover', fields.CharField(null=True, max_length=255)),
                ('backdrop', fields.CharField(null=True, max_length=255)),
                ('rating', fields.DecimalField(null=True, max_digits=4, decimal_places=2)),
            ],
            options={'table': 'media_item', 'app': 'models', 'unique_together': (('lib', 'path'),), 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='User',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('username', fields.CharField(unique=True, max_length=64)),
                ('password', fields.CharField(max_length=64)),
                ('avatar', fields.CharField(null=True, max_length=255)),
                ('role', fields.CharEnumField(description='USER: user\nADMIN: admin', enum_type=UserRole, max_length=16)),
                ('preferences', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
            ],
            options={'table': 'user', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_index=True, db_constraint=True, to_field='id', related_name='favorites', on_delete=OnDelete.CASCADE)),
                ('indexer', fields.ForeignKeyField('models.FlowGraph', source_field='indexer_id', db_index=True, db_constraint=True, to_field='id', related_name='favorites', on_delete=OnDelete.CASCADE)),
                ('rsrc_id', fields.CharField(max_length=255)),
                ('rsrc', fields.JSONField(encoder=JSON_DUMPS, decoder=loads)),
                ('url', fields.CharField(null=True, max_length=255)),
            ],
            options={'table': 'user_favorite', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='UserHistory',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_index=True, db_constraint=True, to_field='id', related_name='histories', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'user_history', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
        ops.CreateModel(
            name='UserSession',
            fields=[
                ('id', fields.IntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(null=True, auto_now=True, auto_now_add=False)),
                ('session_id', fields.CharField(max_length=32)),
                ('user_info', fields.JSONField(encoder=JSON_DUMPS, decoder=loads)),
            ],
            options={'table': 'user_session', 'app': 'models', 'pk_attr': 'id'},
            bases=['TortoiseModel'],
        ),
    ]
